title: Open Source Program Office
description: The homepage for Carnegie Mellon University's Open Source Program Office
theme: just-the-docs

url: https://orthelious.github.io/cmuospo

aux_links:
  Template Repository: https://github.com/orthelious/cmuospo
